I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 196, in script call
    call juyuk_ending from _call_juyuk_ending
  File "game/script.rpy", line 437, in script call
    call share_app from _call_share_app
  File "game/script.rpy", line 451, in script
    $ renpy.android.open_url("file:///admob_ad_sample.html")
  File "game/script.rpy", line 451, in <module>
    $ renpy.android.open_url("file:///admob_ad_sample.html")
AttributeError: 'bool' object has no attribute 'open_url'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 196, in script call
    call juyuk_ending from _call_juyuk_ending
  File "game/script.rpy", line 437, in script call
    call share_app from _call_share_app
  File "game/script.rpy", line 451, in script
    $ renpy.android.open_url("file:///admob_ad_sample.html")
  File "D:\Projects\renpy\renpy-8.3.6-sdk\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Projects\renpy\renpy-8.3.6-sdk\renpy\python.py", line 1184, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 451, in <module>
    $ renpy.android.open_url("file:///admob_ad_sample.html")
AttributeError: 'bool' object has no attribute 'open_url'

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.6.25022803
circle64love 1.0
Tue Mar 11 20:24:45 2025
